[package]
name = "grpc-benchmark"
edition = "2024"
authors = ["gRPC Authors"]
license = "MIT"
rust-version = { workspace = true }

[dependencies]
grpc = { path = "../grpc" }
grpc-protobuf = { path = "../grpc-protobuf" }
prost = "0.14"
protobuf = { version = "4.34.0-release" }
protobuf-well-known-types = { version = "4.34.0-release" }
tonic = { path = "../tonic" }
tonic-prost = { path = "../tonic-prost" }

[build-dependencies]
tonic-prost-build = { path = "../tonic-prost-build" }
grpc-protobuf-build = { path = "../grpc-protobuf-build" }
protobuf-well-known-types = { version = "4.34.0-release" }
